[workspace]

members = [
    "concrete-npe",
    "concrete-core",
    "concrete-csprng",
    "concrete-commons",
    "concrete-tasks",
    "concrete-core-bench",
    "concrete-core-fixture",
    "concrete-core-test",
    "concrete-ffi"
]

[patch.crates-io]
concrete-npe = {path="concrete-npe"}
concrete-core = {path="concrete-core"}
concrete-csprng = {path="concrete-csprng"}
concrete-commons = {path="concrete-commons"}

[profile.release]
lto = "fat"

[profile.bench]
lto = "fat"
