name: concrete-core-ffi GitHub release
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build concrete-core-ffi on Linux
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Build libconcrete_core_ffi
        env:
          RUSTFLAGS: "-Ctarget-feature=+aes,+sse2,+avx,+avx2"
        run: |
          TMP_DIR="$(mktemp -d)"

          ./script/action_utils/concrete-core-ffi-release.sh \
          --rust-toolchain "$(cargo xtask get_build_toolchain | tail -n 1)" \
          --features-string '--features x86_64' \
          --rust-build-dir "$(pwd)/target/release" \
          --output-release-dir "${TMP_DIR}" \
          --sha256-sum-out-file sha256_linux.txt \
          --github-env-file "${GITHUB_ENV}" \
          --release-flavor linux_amd64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_amd64
          path: ${{ env.TO_UPLOAD }}

  build-mac-os:
    name: Build concrete-core-ffi on macOS
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Build libconcrete_core_ffi
        env:
          RUSTFLAGS: "-Ctarget-feature=+aes,+sse2"
        run: |
          TMP_DIR="$(mktemp -d)"

          ./script/action_utils/concrete-core-ffi-release.sh \
          --rust-toolchain "$(cargo xtask get_build_toolchain | tail -n 1)" \
          --features-string '--features x86_64' \
          --rust-build-dir "$(pwd)/target/release" \
          --output-release-dir "${TMP_DIR}" \
          --sha256-sum-out-file sha256_darwin.txt \
          --github-env-file "${GITHUB_ENV}" \
          --release-flavor darwin_amd64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: darwin_amd64
          path: ${{ env.TO_UPLOAD }}

  build-mac-os-apple-silicon:
    name: Build concrete-core-ffi on macOS with M1
    runs-on: ["self-hosted", "m1mac"]
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Rust for tasks
        run: |
          make install_tasks_rust_toolchain
      - name: Build libconcrete_core_ffi
        env:
          RUSTFLAGS: "-Ctarget-cpu=native"
        run: |
          TMP_DIR="$(mktemp -d)"

          ./script/action_utils/concrete-core-ffi-release.sh \
          --rust-toolchain "$(cargo xtask get_build_toolchain | tail -n 1)" \
          --features-string '--features aarch64' \
          --rust-build-dir "$(pwd)/target/release" \
          --output-release-dir "${TMP_DIR}" \
          --sha256-sum-out-file sha256_darwin.txt \
          --github-env-file "${GITHUB_ENV}" \
          --release-flavor darwin_aarch64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: darwin_aarch64
          path: ${{ env.TO_UPLOAD }}
