# Check formatting using rustfmt
# and lint with clippy
name: Rustfmt and Clippy check
on:
  pull_request:
jobs:
  formatting:
    name: rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust for tasks
        run: |
          make install_tasks_rust_toolchain
      - name: Run rustfmt
        run: cargo xtask check_fmt

  clippy-check:
    name: clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust for tasks
        run: |
          make install_tasks_rust_toolchain
      - name: Run clippy
        run: cargo xtask check_clippy

  check-doc:
    name: doc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust for tasks
        run: |
          make install_tasks_rust_toolchain
      - name: Builds doc
        run: cargo xtask check_doc

  cuda-lint-check:
    name: clang-format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust for tasks
        run: |
          make install_tasks_rust_toolchain
      - name: Format concrete-cuda
        run: |
          cargo xtask chore_format
      - name: Check diff
        run: git diff --exit-code

